services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-easy_password}
      - MYSQL_VERSION=${MYSQL_VERSION:-8.4.4}  # 8.4 are LTS versions, maintained until 2032.
      # - DB_CONFIG_AUTO_RELOAD=${DB_CONFIG_AUTO_RELOAD:-FALSE}
    ports:
      - "3306:3306"
    volumes:
      # - ./config/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
      # healthcheck:
      #   test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      #   interval: 10s
      #   retries: 5
